services:
  # Base de Datos
  db:
    image: postgres:15-alpine
    container_name: asescon-db
    restart: always
    environment:
      POSTGRES_USER: user_admin
      POSTGRES_PASSWORD: password_secret
      POSTGRES_DB: asescon_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Backend (NestJS)
  api:
    build: ./backend
    container_name: asescon-api
    restart: always
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: "postgresql://user_admin:password_secret@db:5432/asescon_db"
    depends_on:
      - db

  # Frontend (Next.js)
  web:
    build: ./frontend
    container_name: asescon-web
    restart: always
    ports:
      - "3000:3000"
    environment:
      NEST_API_URL: "http://api:3001"
    depends_on:
      - api

volumes:
  postgres_data:
